---
collections:
  - name: community.general
    version: 10.5.0
  - name: community.sops
    version: 2.0.4
  - name: ansible.posix
    version: 2.0.0
  - name: community.general.timezone
roles:
  - src: xanmanning.k3s
    version: v3.6.2
