---
collections:
  - name: community.general
    version: 8.5.0
  - name: community.sops
    version: 1.7.0
  - name: ansible.posix
    version: 1.5.4
  - name: community.general.timezone
roles:
  - src: xanmanning.k3s
    version: v3.4.4
