apiVersion: v1
kind: Secret
metadata:
    name: ghost-data-restic-config
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ouPu4xeOpWD2C40o2rAdYWykZun2+bP4gz0ggZ2dZzUf8W7SmDbsArKNFB/5G2ZWYuGdFeuUUV/bFgIjSxk=,iv:/VOWvY83NYo70+2cTDZnuRFasNIXSM/8h7WhCOijrww=,tag:r3+nPquKg9Js4MhJjEwrQw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:owjzOoDGmsUL6qCY,iv:QVRolTj5ovA/QCJGz35ebjsVfzyHDET1g5TiH/uOMps=,tag:4TVmX83akFnBZ68BYOUGtA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:tdeb2pzyOaWvPpo3snQ3Jg==,iv:4MQcgs6WdcNafCP4Fp80cBPyUjrUBJR9bfeAWE+eRSY=,tag:I+uvcibgeBonF8xN+NRmKg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Ew32cZXCGx6xxStGUQYeHoe2wBQOhho7cvenKtvht40=,iv:qfw7O5ztOIHO37/JQ69Uu7vfZHUbBXT242bM2k/ioyA=,tag:mDJeG06eXlW41pGrTyd2gw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fl92uj8fwujcphes4cxm82qlztxf4kh6j0d2a9at7alpml266p3sedrvx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYnRiWjBVeUhpYmFjNnRa
            T1V1cG80cVRaaisrVGx4WGxpclJRSFZBaUVzCmJrQ3F4WHpKN0xCQ0pDRmFyc0NU
            enJYM2RJcDB2Nk4xZGpyTm5wbHliK0kKLS0tIHhpNldnVW50bmJTak9yS1NGTjFv
            Y254M20vdy9BRDdDbWFCVTNOU0FYRzAKGdcGGVGL0KH5kXeaC9JrE1MTpawDRgnt
            46riqTXDyohEfGp5iIZy+1h2z1FyRjQO7zWRJt2/UU8D+Ihho+Lm3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-15T22:11:00Z"
    mac: ENC[AES256_GCM,data:ievSgfFF5+kAXWm9p1HGNeUbOLMlUBjJ+dOmQ7VEtDbpxWEyf2wQc2/L/HZRtfJejWYpGTpphDj7kRXaFx+CDgWZUCXd4sk4V1bdjzHL81r65/gV6XZItYYlLD75u13Ic51M/dE+jf9en6CWc7N6Ll9tDI43sPXn7NLli5kJvQo=,iv:dp+dx2ZDaQ36I6XjGkztLOg0UkBZnlgzutbbwk7CURY=,tag:UdQxgFwLF2VGFBIqG1SnDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
