---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: frequent-backup
  namespace: longhorn-system
spec:
  cron: "0 */8 * * *"
  task: "backup"
  parameters:
    full-backup-interval: "9"
  groups:
    - frequent
  retain: 21
  concurrency: 3
