---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-passport-database
  namespace: flux-system
spec:
  path: ./kubernetes/apps/production/passport/passport/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-source
  interval: 30m
  retryInterval: 1m
  timeout: 3m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cluster-apps-passport
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: cluster-apps-passport-database
#   path: ./kubernetes/apps/production/passport/passport/app
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: homelab-source
#   interval: 30m
#   retryInterval: 1m
#   timeout: 3m
