apiVersion: v1
kind: Secret
metadata:
    name: minecraft-data-hb-restic-config
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ikGt6NmkWcbXflUQ5yHaFbAZ9MAjB7oSLtz8Vu8dvwYthC0y9bZkaxiv4ufpAL/gx9L+bPM+E/NZbZp1kiu4CFVZh9MGX2r3E9DZdE8=,iv:d2U4+Ffd62idPIMKFe3USzSh+Bl+BLQMGwurp6Fv7M8=,tag:qecJntmos0QkmnNNPSHk0A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:oD9Frf5RNKuvyYm0wDI=,iv:br6glnPkH+TAiTMet7ZotNCORVWv+s2RSNvmECM4XQU=,tag:unCUAt34vHBU1Zd7tI+PyQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:tdeb2pzyOaWvPpo3snQ3Jg==,iv:4MQcgs6WdcNafCP4Fp80cBPyUjrUBJR9bfeAWE+eRSY=,tag:I+uvcibgeBonF8xN+NRmKg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Ew32cZXCGx6xxStGUQYeHoe2wBQOhho7cvenKtvht40=,iv:qfw7O5ztOIHO37/JQ69Uu7vfZHUbBXT242bM2k/ioyA=,tag:mDJeG06eXlW41pGrTyd2gw==,type:str]
sops:
    age:
        - recipient: age1fl92uj8fwujcphes4cxm82qlztxf4kh6j0d2a9at7alpml266p3sedrvx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYnRiWjBVeUhpYmFjNnRa
            T1V1cG80cVRaaisrVGx4WGxpclJRSFZBaUVzCmJrQ3F4WHpKN0xCQ0pDRmFyc0NU
            enJYM2RJcDB2Nk4xZGpyTm5wbHliK0kKLS0tIHhpNldnVW50bmJTak9yS1NGTjFv
            Y254M20vdy9BRDdDbWFCVTNOU0FYRzAKGdcGGVGL0KH5kXeaC9JrE1MTpawDRgnt
            46riqTXDyohEfGp5iIZy+1h2z1FyRjQO7zWRJt2/UU8D+Ihho+Lm3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T18:20:48Z"
    mac: ENC[AES256_GCM,data:Zqb6vEF6jlvrmM4p0lE2JbbitM/S10JWwTTMPCwGGb3WHvwPpajYVvigTWAhLE3edvo0iRjcWF5m/Im/87yzyWk+DtjQGmlYpg63NtQMVvlwX81w1KyEmZyaiiJCPilr/xlkXRYeVIksHnvpxoSFRW3xuwVmyvTQVaJ4kwa/fMU=,iv:zvcm7ZeIJjTBGQ/kN+46LN8e479Xzdh23mNjpX0DH3w=,tag:5Ckbf4cyfR4S3QAKvKV1ZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
