---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: minecraft-data
spec:
  sourcePVC: minecraft-datadir
  trigger:
    schedule: "35 7 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: minecraft-data-hb-restic-config
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    storageClassName: ceph-block
    retain:
      daily: 7
      weekly: 4
      monthly: 12
      yearly: 10
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: minecraft-data-to-phx
spec:
  sourcePVC: minecraft-datadir
  trigger:
    schedule: "40 7 * * *"
  restic:
    unlock: "unlock-11-28-2025"
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: minecraft-data-phx-restic-config
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    storageClassName: ceph-block
    retain:
      daily: 7
      weekly: 4
      monthly: 12
      yearly: 10
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: minecraft-data-to-sj
spec:
  sourcePVC: minecraft-datadir
  trigger:
    schedule: "45 7 * * *"
  restic:
    unlock: "unlock-11-28-2025"
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: minecraft-data-sj-restic-config
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    storageClassName: ceph-block
    retain:
      daily: 7
      weekly: 4
      monthly: 12
      yearly: 10
