---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgresql-vsc-backup
spec:
  schedule: "0 0 7 * * 0"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: authentik-postgresql
  method: volumeSnapshot