---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infrastructure-cilium
  namespace: flux-system
spec:
  path: ./kubernetes/infrastructure/staging-sj/kube-system/cilium/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-source
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cilium
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infrastructure-wildcard-certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-infrastructure-cilium
  path: ./kubernetes/infrastructure/staging-sj/kube-system/cilium/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-source
  interval: 30m
  retryInterval: 1m
  timeout: 5m
