---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  image: docker-registry1.mariadb.com/library/mariadb:12.2.2
  rootPasswordSecretKeyRef:
    name: bookstack-mariadb-password
    key: PASSWORD
  username: bookstack
  passwordSecretKeyRef:
    name: bookstack-mariadb-password
    key: PASSWORD
  database: bookstack
  storage:
    size: 12Gi
    storageClassName: ceph-block
