---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-sonarqube-database
  namespace: flux-system
spec:
  path: ./kubernetes/apps/production/development/sonarqube/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-source
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-sonarqube
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-sonarqube-database
  path: ./kubernetes/apps/production/development/sonarqube/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-source
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: sonarqube
      namespace: development
  interval: 30m
  retryInterval: 1m
  timeout: 10m
