---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./bookstack/ks.yaml
  - ./planka/ks.yaml
  - ./pocketbase/ks.yaml
  - ./harbor/ks.yaml
  - ./gitea/ks.yaml
  - ./bitbucket/ks.yaml
  - ./jenkins/ks.yaml
  - ./sonarqube/ks.yaml
  - ./nexus/ks.yaml
  - ./docs-server/ks.yaml
  # - ./fake-metrics-generator/ks.yaml
  # - ./cluster-status-api/ks.yaml
  # - ./rsyslog-server/ks.yaml
  # - ./oci-instance-creator/ks.yaml
  # - ./fifa-openapi/ks.yaml
