---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  chart:
    spec:
      version: 2.0.2
  values:
    controller:
      volumeSnapshotClasses:
        - name: csi-rbdplugin-snapclass
          driver: rook-ceph.rbd.csi.ceph.com
          annotations:
            snapshot.storage.kubernetes.io/is-default-class: "true"
          parameters:
            clusterID: rook-ceph
            csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph
          deletionPolicy: Delete
        - name: csi-cephfsplugin-snapclass
          driver: rook-ceph.cephfs.csi.ceph.com
          annotations:
            snapshot.storage.kubernetes.io/is-default-class: "true"
          parameters:
            clusterID: rook-ceph
            csi.storage.k8s.io/snapshotter-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph
          deletionPolicy: Delete
      serviceMonitor:
        create: false
