---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: home-assistant-oidc-redirect
spec:
  redirectRegex:
    regex: ".*"
    replacement: "https://home.${SECRET_DOMAIN}/auth/oidc/welcome"
    permanent: false
