---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium/ks.yaml
  # - ./metrics-server/ks.yaml
  # - ./snapshot-controller/ks.yaml
  # - ./coredns/ks.yaml
  # - ./reloader/ks.yaml
