---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: firefly-authentik-ingress-route
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`firefly.${SECRET_DOMAIN}`)
      priority: 10
      middlewares:
        - name: authentik
          namespace: networking
      services:
        - kind: Service
          name: firefly-iii
          namespace: finance
          port: 80
    - kind: Rule
      match: "Host(`firefly.${SECRET_DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      services:
        - kind: Service
          name: ak-outpost-authentik-embedded-outpost
          namespace: security
          port: 9000
  tls:
    secretName: firefly-tls
