---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sonarqube
  namespace: flux-system
spec:
  interval: 30m
  url: https://SonarSource.github.io/helm-chart-sonarqube
  timeout: 3m
