apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:uAIphBbyDkzi,iv:+9IrUpS7oYqQdiNi3Qw5oF/DaoeFqEokIvzNetEAKkk=,tag:CTHTCjtIkY5lKOTYCK02CQ==,type:str]
    password: ENC[AES256_GCM,data:JudqMPnH6ytEV8B+QCo=,iv:n7PVNhcc9Pm2LMe+gVLCn1v2Cs9uW/7ZmedPOxdnQd4=,tag:a7d4n59FzoGgUDh+NP3Uig==,type:str]
sops:
    age:
        - recipient: age1fl92uj8fwujcphes4cxm82qlztxf4kh6j0d2a9at7alpml266p3sedrvx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveGVUYU10VzVuZGtMMlBy
            ZWtxTkpoYXNweTVyWFZpR3ZHKytLZVlXTkYwCi9Gdis1d2VUVnpJY2dRMUtmbklV
            R0Z6ajlLekF2SWJiSGtJVXlTYlNYTjgKLS0tIGRHc0duSGtPZm1LalQ2ZnlvcXNY
            djUwS1NDa3JOTGRnWFNoTE5iMWt1K0EKHYk2glp5rBvG3OfQvvvuAHLmRMcFrm3+
            Is+JxXzhYxBGkP8s4+FvIRy+Z5kkR+37+EFGtkFgpiwLaTQXG2r07g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T23:49:12Z"
    mac: ENC[AES256_GCM,data:hI9J7ZcEx1O4og9m83/FM2Q9crg2HzBomQ9qfNb5wNDMt6uX1AnwvAWI6+JLf8UbnEaGAE6RqjBTqyPEy2UQTGEo7ebG4b/0Q0T6VbPY59w3HexBANR3NXodRxmnOq1exC/FZGqlRTkv5ZUvcqwsE2pQMvWtk+PJ9XBI9Nyrhr0=,iv:761PiLugeOYE4MjpRxP/d+l4JczlRvUulzaTu2/VukM=,tag:iy0clro4AvHpwjhiRgOG2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
