---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./secrets
  - ./namespace.yaml
  - ./home-assistant/ks.yaml
  - ./commute-dashboard/ks.yaml
  - ./commute-dashboard-2/ks.yaml
  # - ./af-usage/ks.yaml
  # - ./wyze-bridge/ks.yaml
  # - ./pihole-hue-bridge/ks.yaml
