---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: passport
resources:
  # - ./restic-config.sops.yaml
  # - ./volsync.yaml
  - ./postgresql-secret.sops.yaml
  - ./postgresql.yaml
namePrefix: passport-
