apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:hutSHMD+FKw=,iv:X4JlHWy7No29dKjVCk2iqf4xT8Xt26YL30XyXhVBJ68=,tag:GvYRgHh1RJXpMX+JmkTOMQ==,type:str]
    password: ENC[AES256_GCM,data:oOK+fx9vNgKU7jgHxKw=,iv:cMKEV+k444EBjf9qlToSpchhZ20+ZGvbe0m29tZTDHc=,tag:Ae02cAXEe5gU4OnD4U6VLQ==,type:str]
sops:
    age:
        - recipient: age1fl92uj8fwujcphes4cxm82qlztxf4kh6j0d2a9at7alpml266p3sedrvx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YVNiaVpPamF5TGxuNHV1
            UTQvRjAvc1FaK0dXODYrRTQ3MUZJS2Yxa2hJCkhvM2MvZ2JDTDVvM2lCM2lWY0Nx
            dTFCZWlUK3YzV3hBaUp6QlJyWlgzdTQKLS0tIHJTcDRBSElwWDlPSkVpVis1YnpD
            aTBFandQZWdjd2dDVVpuOVdvT0o4ZkUKNQTFCcvg8vH63LhIhEgtRCVJHHU41ZIX
            6oXdQvMpaJJEGOI4UDqP635awHtWAQYxvXxftRAhsp5T52BWFRxjVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T22:28:23Z"
    mac: ENC[AES256_GCM,data:60PBLbEHBHynF4Iv/HgPSwM+CwQkDpeKSCNpNs4wHF7tYq+TGiNtugkynKVzI+DvVJKd8U9JQHEQapkpG8Abrha1x0i3dDhfFqA95jafqdVgb0dVFRe+gQa1e7Dwn2hlLvu+ycXITBN2NOgjQ0X2+VDnqOjMOWnBLCjJtUi9lXo=,iv:WWkh/RFHOHD9onJ/P7MjccApzGm7KEKSZusBILGHkns=,tag:r0noSy+KSOApvfck5R6NlQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
