---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./thanos/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./grafana/ks.yaml
  - ./scrutiny/ks.yaml
  - ./vpa/ks.yaml
  # - ./goldilocks/ks.yaml
