---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: games
resources:
  - ./mariadb-secret.sops.yaml
  - ./mariadb.yaml 
  # - ./backup.yaml
  # - ./restic-config.sops.yaml
  # - ./oci-phx-restic-config.sops.yaml
  # - ./volsync.yaml
namePrefix: bluemap-
