---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  image: docker-registry1.mariadb.com/library/mariadb:12.2.2
  rootPasswordSecretKeyRef:
    name: bluemap-mariadb-password
    key: PASSWORD
  username: bluemap
  passwordSecretKeyRef:
    name: bluemap-mariadb-password
    key: PASSWORD
  database: bluemap
  storage:
    size: 16Gi
    storageClassName: ceph-block
