apiVersion: v1
kind: Secret
metadata:
    name: mariadb-password
type: Opaque
stringData:
    PASSWORD: ENC[AES256_GCM,data:OdZwjzxxI1gNPCNMHhs=,iv:1hDMesmp02yEO6swpjlpkiIlRmiAKGJrMIeEaErPfp8=,tag:B/XdVL8PZCfYMYs+kPv0aA==,type:str]
sops:
    age:
        - recipient: age1fl92uj8fwujcphes4cxm82qlztxf4kh6j0d2a9at7alpml266p3sedrvx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYb2JVRWE3SGtSZkVycGYr
            YXhiWlNKRTFmSUM3WU5ZV3RTa1Z5RVdlMkFZCklscXg4QVVVT0tNTVVORE9CTHo3
            dTNTMk1ub2lWREVPSUFTOENYYk8rczgKLS0tIHNnMThsVytMNjF0emhWSy9zTC91
            NlZab3NaVFp3MUoza01odml3aE9iVk0KIlbDbjhGSxr0o8yqOois5jZz1Ogn+epW
            2XsKni9254W6JfsjtnnFQmZZIUmq9i0dmlH+M2fwg5a5TZ/mIiFXbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T06:11:35Z"
    mac: ENC[AES256_GCM,data:GSQaL24piTwjdpEaE4VxBs9Zt7T6pbttCRXV7q2eJFhZ5yvIa8dcWKd74kGb9nbXsIG/30aoXtPfi0M6PsyjtWhd0GR2wJmnrVx7yMBeSx9RAsbkz3m/H2Ubm9PPtKuW4f6YGCMi3UX01Ty8HVE4z5Qo1WqIZk0XD4yj+2deAlg=,iv:APoxRK+133M1tAGLjyCG2gmkPIEixNo5k7QQByIChew=,tag:ROQvmgncM7f77M98lAVl7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
