---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bitnami-redis
  namespace: flux-system
spec:
  interval: 30m
  url: oci://registry-1.docker.io/bitnamicharts/redis
  ref:
    tag: "25.3.0"
