---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./data-pvc.yaml
  - ./restic-config.sops.yaml
  - ./volsync.yaml
  - ../../../../base/uptime-kuma
patches:
  - path: ./uptime-kuma-values.yaml
