---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-baserow-database
  namespace: flux-system
spec:
  path: ./kubernetes/apps/staging-phx/magazine/baserow/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-source
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: baserow-postgresql
      namespace: magazine
  interval: 30m
  retryInterval: 1m
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-baserow-redis
  namespace: flux-system
spec:
  path: ./kubernetes/apps/staging-phx/magazine/baserow/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-source
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: baserow-redis
      namespace: magazine
  interval: 30m
  retryInterval: 1m
  timeout: 10m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cluster-apps-baserow
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: cluster-apps-baserow-redis
#     - name: cluster-apps-baserow-database
#   path: ./kubernetes/apps/staging-phx/magazine/baserow/app
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: homelab-source
#   healthChecks:
#     - apiVersion: helm.toolkit.fluxcd.io/v2beta1
#       kind: HelmRelease
#       name: baserow
#       namespace: magazine
#   interval: 30m
#   retryInterval: 5m
#   timeout: 10m
